 create table paycomet_notification (
       order_number varchar2(255 char) not null,
        account_code varchar2(255 char) not null,
        amount number(10,0) not null,
        amount_eur number(10,0) not null,
        auth_code varchar2(255 char) not null,
        bank_date_time varchar2(255 char) not null,
        bic_code varchar2(255 char) not null,
        card_brand varchar2(255 char) not null,
        card_country varchar2(255 char) not null,
        concept varchar2(255 char) not null,
        currency varchar2(255 char) not null,
        error_description varchar2(255 char) not null,
        error_id number(10,0) not null,
        id_user number(10,0) not null,
        notification_hash varchar2(255 char) not null,
        response varchar2(255 char) not null,
        scoring number(10,0) not null,
        secure_payment varchar2(255 char) not null,
        token_user varchar2(255 char) not null,
        tpv_id number(10,0) not null,
        transaction_name varchar2(255 char) not null,
        transaction_type number(10,0) not null,
        primary key (order_number)
    );