INSERT INTO USUARI VALUES(1,'admin','$2a$10$lLGi1t0OT7ftruz8ieC2B.ImwpGTlkVCHDiYrQKTYdlOr6fN/CFMa','admin@limit.es',NULL,'Administrador',1,1,0);
INSERT INTO USUARI_AUTHORITIES VALUES(1,'ADMIN');
SELECT HIBERNATE_SEQUENCE.NEXTVAL FROM DUAL;
INSERT INTO USUARI VALUES(2,'test','$2a$10$DOpxYy8VGZcKnW6aA9y4uO17KpIMFCpZRqlYjHFlFo5R/pM354g52','test@limit.es',NULL,'Test',1,1,0);
INSERT INTO USUARI_AUTHORITIES VALUES(2,'MARCA');
SELECT HIBERNATE_SEQUENCE.NEXTVAL FROM DUAL;
INSERT INTO USUARI VALUES(3,'sync','$2a$10$j.zqnsIS6LEM/0hhIbTfS.gxd80WMl3nx0azivywrIdnTkRhrOghG','sync@limit.es',NULL,'Sincronització CECOGEST',1,1,0);
INSERT INTO USUARI_AUTHORITIES VALUES(3,'SYNC');
SELECT HIBERNATE_SEQUENCE.NEXTVAL FROM DUAL;
