/*
INSERT INTO USUARI VALUES(1,'admin','$2a$10$lLGi1t0OT7ftruz8ieC2B.ImwpGTlkVCHDiYrQKTYdlOr6fN/CFMa','admin@limit.es',NULL,'Administrador',true, 0)
INSERT INTO USUARI_ROLS VALUES(1,'ADMIN')
ALTER SEQUENCE PUBLIC.HIBERNATE_SEQUENCE RESTART WITH 2
*/