/*
INSERT INTO USUARI VALUES(1,'admin','$2y$12$a5DTeN3j/qrcxDOJGJkufOYbyHxRcsuOtenwhmZP4nFIYS/3VtK9e','admin@limit.es',NULL,'Administrador',true, 0)
INSERT INTO USUARI_ROLS VALUES(1,'ADMIN')
ALTER SEQUENCE PUBLIC.HIBERNATE_SEQUENCE RESTART WITH 2
*/