#!/bin/sh
cd $(dirname $0)
cat ./cecogest/LIMIT.SQL \
./cecogest/GUSUARIS.SQL \
./cecogest/CECOBANC.SQL \
./cecogest/CONTACEC.SQL \
./cecogest/RRMM.SQL \
./cecogest/RRHH.SQL \
./cecogest/CECOGEST.SQL > cecogest_db.sql
