create sequence hibernate_sequence start with 1 increment by 1;

create table companyia (
   id bigint not null,
    codi varchar(30) not null,
    nom varchar(30) not null,
    version bigint not null,
    primary key (id)
);

create table empresa (
   id bigint not null,
    version bigint not null,
    activa boolean not null,
    codi varchar(30) not null,
    identificador_codi varchar(4) not null,
    nif varchar(12) not null,
    nom varchar(30) not null,
    companyia_id bigint,
    primary key (id)
);

create table marcatge (
   id bigint not null,
    operari_id bigint not null,
    data timestamp not null,
    latitud double,
    longitud double,
    origen integer not null,
    created_by varchar(64) not null,
    created_date timestamp not null,
    lastmod_by varchar(64),
    lastmod_date timestamp,
    version bigint not null,
    primary key (id)
);

create table usuari (
   id bigint not null,
    codi varchar(64) not null,
    contrasenya varchar(255),
    email varchar(100) not null,
    imatge_url varchar(255),
    nom varchar(100) not null,
    validat boolean,
    actiu boolean,
    version bigint not null,
    primary key (id)
);

create table operari (
   id bigint not null,
    data_fi timestamp,
    data_inici timestamp not null,
    codi varchar(6) not null,
    version bigint not null,
    usuari_id bigint not null,
    empresa_id bigint not null,
    primary key (id)
);

create table usuari_rols (
   usuari_id bigint not null,
    rol varchar(10)
);

alter table usuari 
   add constraint usuari_codi_uk unique (codi);

alter table usuari 
   add constraint usuari_email_uk unique (email);

alter table empresa 
   add constraint empresa_companyia_fk 
   foreign key (companyia_id) 
   references companyia;

alter table marcatge 
   add constraint marcatge_operari_fk 
   foreign key (operari_id) 
   references operari;

alter table operari 
   add constraint operari_usuari_fk 
   foreign key (usuari_id) 
   references usuari;

alter table operari 
   add constraint operari_empresa_fk 
   foreign key (empresa_id) 
   references empresa;

alter table usuari_rols 
   add constraint usurol_usuari_fk 
   foreign key (usuari_id) 
   references usuari;

create table acl_sid(
    id bigint generated by default as identity(start with 100) not null primary key,
    principal boolean not null,
    sid varchar_ignorecase(100) not null,
    constraint unique_uk_1 unique(sid,principal)
);

create table acl_class(
    id bigint generated by default as identity(start with 100) not null primary key,
    class varchar_ignorecase(100) not null,
    constraint unique_uk_2 unique(class)
);

create table acl_object_identity(
    id bigint generated by default as identity(start with 100) not null primary key,
    object_id_class bigint not null,
    object_id_identity varchar_ignorecase(36) not null,
    parent_object bigint,
    owner_sid bigint,
    entries_inheriting boolean not null,
    constraint unique_uk_3 unique(object_id_class,object_id_identity),
    constraint foreign_fk_1 foreign key(parent_object)references acl_object_identity(id),
    constraint foreign_fk_2 foreign key(object_id_class)references acl_class(id),
    constraint foreign_fk_3 foreign key(owner_sid)references acl_sid(id)
);

create table acl_entry(
    id bigint generated by default as identity(start with 100) not null primary key,
    acl_object_identity bigint not null,
    ace_order int not null,
    sid bigint not null,
    mask integer not null,
    granting boolean not null,
    audit_success boolean not null,
    audit_failure boolean not null,
    constraint unique_uk_4 unique(acl_object_identity,ace_order),
    constraint foreign_fk_4 foreign key(acl_object_identity) references acl_object_identity(id),
    constraint foreign_fk_5 foreign key(sid) references acl_sid(id)
);
